/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Hp
 */
public class JPanelViewPeminjamanAdmin extends javax.swing.JPanel {
private Runnable updateListener;
    DefaultTableModel tabelmodel; 
    Connection con=null; 
    Statement stat; 
    ResultSet res; 
    PreparedStatement pst = null; 
    String cekconeks; 
    
    /**
     * Creates new form JPanelViewPeminjamanAdmin
     */
    public JPanelViewPeminjamanAdmin() {
        initComponents();
        koneksi();
        datatojtable();
    }
    
        public void setUpdateListener(Runnable listener) {
    this.updateListener = listener;
}

private void triggerUpdate() {
    if (updateListener != null) {
        updateListener.run();
    }
}

public void refreshData() {
        datatojtable();

    }
    
     private void koneksi(){ 
            try { 
               Class.forName("com.mysql.cj.jdbc.Driver"); 
               con=DriverManager.getConnection("jdbc:mysql://localhost/dbperpustakaan", "root", ""); 
               stat=con.createStatement();
               } catch (ClassNotFoundException | SQLException e) { 
                   JOptionPane.showMessageDialog(null, e); 
               } 
               }
     
     public void Bersihkan() {
         jTextIdPeminjaman.setText("");
         jTextIdPeminjaman.requestFocus();
     }
     
     public void datatojtable() 
{ 
DefaultTableModel tb= new DefaultTableModel(); 
// Memberi nama pada se�ap kolom tabel 
tb.addColumn("Id Peminjaman"); 
tb.addColumn("Id Anggota"); 
tb.addColumn("Nama Anggota"); 
tb.addColumn("Kode Eksemplar"); 
tb.addColumn("Nama Buku"); 
tb.addColumn("Tanggal Pinjam"); 
tb.addColumn("Tanggal Jatuh Tempo");   
jTablePeminjaman.setModel(tb); 
try{ 
// Mengambil data dari database
  res=stat.executeQuery("select * from tpeminjaman"); 
        
 
        while (res.next()) 
        { 
        // Mengambil data dari database berdasarkan nama kolom pada tabel 
            // Lalu di tampilkan ke dalam JTable 
            tb.addRow(new Object[]{ 
            res.getString("IdPeminjaman"), 
            res.getString("IdAnggota"), 
            res.getString("NamaAnggota"), 
            res.getString("KodeEksemplar"), 
            res.getString("NamaBuku"), 
            res.getTimestamp("TanggalPinjam"), 
            res.getTimestamp("TanggalJatuhTempo"), 
           }); 
          } 
         Aturkolom(); //pemanggilan class untuk mengatur kolom 
         
        }catch (SQLException e){ 
        } 
        
    }  
     
     private void Aturkolom() 
    { 
        TableColumn column; 
        jTablePeminjaman.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF); 
        column = jTablePeminjaman.getColumnModel().getColumn(0); 
        column.setPreferredWidth(75); 
        column = jTablePeminjaman.getColumnModel().getColumn(1); 
        column.setPreferredWidth(200); 
        column = jTablePeminjaman.getColumnModel().getColumn(2); 
        column.setPreferredWidth(100); 
        column = jTablePeminjaman.getColumnModel().getColumn(3); 
        column.setPreferredWidth(75); 
        column = jTablePeminjaman.getColumnModel().getColumn(4); 
        column.setPreferredWidth(75);     
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextIdPeminjaman = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePeminjaman = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("VIEW PEMINJAMAN");

        jLabel2.setText("ID PEMINJAMAN");

        jTablePeminjaman.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablePeminjaman);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextIdPeminjaman))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextIdPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePeminjaman;
    private javax.swing.JTextField jTextIdPeminjaman;
    // End of variables declaration//GEN-END:variables
}
